name: Train Wishlist Model

on:
  push:
    branches: [main]
    paths:
      - 'analytics/data/wishlist_sample.csv'
  pull_request:
    branches: [main]
    paths:
      - 'analytics/data/wishlist_sample.csv'

permissions:
  contents: write

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install faker joblib scikit-learn pandas

      - name: Train model
        run: python analytics/src/model_trainer.py

      - name: Test gift predictor
        run: python analytics/src/gift_predictor.py

      - name: Commit trained model and encoder
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add analytics/models/*.pkl
          git commit -m "Auto: update model on data change" || echo "No changes to commit"
          git push
